Add hipchat notification endpoint

diff --git a/app/views/scripts/staging_deploy.erb b/app/views/scripts/staging_deploy.erb
--- a/app/views/scripts/staging_deploy.erb
+++ b/app/views/scripts/staging_deploy.erb
@@ -58,3 +58,27 @@ EOF
 
   heroku config:add CIRCLE_SHA1=${CIRCLE_SHA1} CIRCLE_BRANCH=${CIRCLE_BRANCH} --app ${HEROKU_APP_NAME}
 }
+
+function notify() {
+  if [ "$#" -ne 1 ]; then
+    echo "useage: notify([ROOM])"
+    exit 1
+  fi
+
+  if [ "${HIPCHAT_API_TOKEN}" == "" ]; then
+    echo "failed to get hipchat api token"
+    exit 1
+  fi
+
+  HEROKU_APP_NAME=`curl <%= ENV['DEPLOY_SUPPORT_TOOL_URL'] %> --data "app=${STAGING_APP_PREFIX}&branch=${CIRCLE_BRANCH}&servers=${NUM_OF_STAGING_SERVERS}"`
+
+  if [ "${HEROKU_APP_NAME}" == "" ]; then
+    echo "failed to get a staging app name"
+    exit 1
+  fi
+
+  ROOM=$1
+  URL="https://${HEROKU_APP_NAME}.herokuapp.com"
+
+  curl <%= ENV['DEPLOY_SUPPORT_TOOL_URL'] %> --data "room=${ROOM}&branch=${CIRCLE_BRANCH}&url=${URL}&token=${HIPCHAT_API_TOKEN}"
+}
